### ISSUE TITLE
Settings for the Sparsity experiment

### ISSUE THREAD

**Issue by liu-yikang** [iffsid/disentangling-disentanglement#1]
Hello. I have a question about the settings for the Sparsity experiment. Please correct me if I am wrong, but shouldn't the 'prior' option be 'Sparse' according to your paper? 'sparsity.sh' uses the default setting 'Normal'.  Thanks.

**Comment by emilemathieu** [comment]
Hello!

I agree it is slightly confusing, but the model `fashion_mnist ` does use the Sparse prior by default;
`sparsity.sh` has the argument `--model fashion_mnist` and in [`models/vae_fashion_mnist.py`](https://github.com/iffsid/disentangling-disentanglement/blob/public/src/models/vae_fashion_mnist.py#L100) we can see the `Sparse` is used by default for the prior.

Hope this clarifies the situation :)

Cheers
Emile
